name: Manual Deploy to AWS

on:
  workflow_dispatch:
    inputs:
      indexerGitHash:
        description: 'engagemint-indexer git commit short hash (e.g. 2e8d24d)'
        required: true
      apiGitHash:
        description: 'engagemint-api git commit short hash (e.g. 2e8d24d)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-west-2'

      - name: Deploy to AWS
        run: API_GIT_HASH=${{ github.event.inputs.apiGitHash }} INDEXER_GIT_HASH=${{ github.event.inputs.indexerGitHash }} yarn deploy --require-approval never
